# Podfile
platform :ios, '9.0'
use_frameworks!

target 'PhahTaigi' do
    pod 'RealmSwift'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Haptica'
    pod 'Firebase/Core'
    pod 'Fabric', '~> 1.9.0'
    pod 'Crashlytics', '~> 3.12.0'
end
