# Podfile
platform :ios, '9.0'
use_frameworks!

target 'PhahTaigi' do
  pod 'RealmSwift', '10.14'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Haptica'
  pod 'Firebase/Core'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
end
